---
# tasks file for roles/imbicile.kms
- name: Install
  ansible.builtin.import_tasks: install.yml
- name: Configure
  ansible.builtin.import_tasks: configure.yml

- name: Ensure kms service is started and enabled
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: vlmcsd.service
    state: started
    enabled: true
    masked: false
